### ISSUE TITLE
semanticreleasenotes.org is down and I can't remember the syntax

### ISSUE THREAD

**Issue by scottcowan** [laedit/SemanticReleaseNotesParser#29]
I'd like to use your parser but the documentation site is down.

do you have a backup of this?

**Comment by scottcowan** [comment]
I found it over at [https://github.com/avanderhoorn/Semantic-Release-Notes](https://github.com/avanderhoorn/Semantic-Release-Notes), but it would be nice to have a link there

**Comment by scottcowan** [comment]
And better yet, here's a link that renders the html for you

http://htmlpreview.github.io/?https://github.com/avanderhoorn/Semantic-Release-Notes/blob/master/index.html

**Comment by laedit** [comment]
Thanks for your interest, sadly I am not the owner of the http://www.semanticreleasenotes.org/ website, only of this tool.
I will add a link to the backup in the readme file, but an issue on the website's repo should be more useful.

There are also some example in my tests: https://github.com/laedit/SemanticReleaseNotesParser/tree/master/src/SemanticReleaseNotesParser.Core.Tests

If you want a tool that generates that format, there is https://github.com/GitTools/GitReleaseNotes which is "almost" compliant 😉
